id = "dazzle"
name = "Dazzle"
version = "0.1.0"
schema_version = 1
description = "A dark theme with vibrant colors"
repository = "https://github.com/erik/dazzle"
authors = ["erik <erik@reges.se>"]
themes = ["dazzle/dazzle.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]
